import { randomBytes, createCipheriv, createDecipheriv } from 'crypto';
import { Buffer } from 'buffer';

/**
 * Structured container for AES-256-GCM output payload assets.
 */
export interface EncryptedPayload {
    /** The encrypted data formatted as a hex string. */
    ciphertext: string;
    /** The unique 12-byte initialization vector formatted as a hex string. */
    iv: string;
    /** The 16-byte authentication tag generated by the GCM cipher. */
    authTag: string;
}

/**
 * Implements authenticated symmetric encryption primitives using AES-256-GCM.
 * Ensures data confidentiality and cryptographic integrity verification.
 * @author Kevin Matarewicz
 */
export class SymmetricEngine {
    private static readonly ALGORITHM = 'aes-256-gcm';
    private static readonly IV_LENGTH = 12; // Standard recommended IV length for GCM
    private static readonly KEY_LENGTH = 32; // 256 bits

    /**
     * Generates a cryptographically secure random 256-bit symmetric key.
     * @returns A 32-byte Buffer containing the raw key material.
     */
    public static generateKey(): Buffer {
        return randomBytes(this.KEY_LENGTH);
    }

    /**
     * Encrypts a plaintext string using AES-256-GCM.
     * @param plaintext The raw string data to encrypt.
     * @param key The 32-byte symmetric encryption key.
     * @returns The structured EncryptedPayload object.
     */
    public static encrypt(plaintext: string, key: Buffer): EncryptedPayload {
        if (key.length !== this.KEY_LENGTH) {
            throw new Error(`Invalid key length. Symmetric key must be exactly ${this.KEY_LENGTH} bytes.`);
        }

        // Generate a unique Initialization Vector (IV) for this specific operation
        const iv = randomBytes(this.IV_LENGTH);
        const cipher = createCipheriv(this.ALGORITHM, key, iv);

        let ciphertext = cipher.update(plaintext, 'utf8', 'hex');
        ciphertext += cipher.final('hex');

        // Extract the authentication tag generated by GCM mode
        const authTag = cipher.getAuthTag().toString('hex');

        return {
            ciphertext,
            iv: iv.toString('hex'),
            authTag
        };
    }

    /**
     * Decrypts an AES-256-GCM payload and verifies its integrity tag.
     * @param payload The structured bundle containing ciphertext, iv, and authTag.
     * @param key The 32-byte symmetric encryption key.
     * @returns The original decrypted plaintext string.
     * @throws Error if the data has been altered or the authentication tag is invalid.
     */
    public static decrypt(payload: EncryptedPayload, key: Buffer): string {
        if (key.length !== this.KEY_LENGTH) {
            throw new Error(`Invalid key length. Symmetric key must be exactly ${this.KEY_LENGTH} bytes.`);
        }

        const ivBuffer = Buffer.from(payload.iv, 'hex');
        const tagBuffer = Buffer.from(payload.authTag, 'hex');
        
        const decipher = createDecipheriv(this.ALGORITHM, key, ivBuffer);
        decipher.setAuthTag(tagBuffer);

        let plaintext = decipher.update(payload.ciphertext, 'hex', 'utf8');
        plaintext += decipher.final('utf8');

        return plaintext;
    }
}